//! PDF simple-font encoding tables (ISO 32000-1 Annex D) and the Adobe
//! Glyph List subset needed to resolve their glyph names to Unicode.
//!
//! Data provenance: ISO 32000-1 Annex D.1/D.2 (the standard's own
//! WinAnsiEncoding and MacRomanEncoding tables) plus Adobe's published
//! [Adobe Glyph List](https://github.com/adobe-type-tools/agl-aglfn)
//! (BSD-3-Clause). The tables were generated mechanically from those
//! sources and cross-checked against Python's `cp1252` / `mac_roman`
//! codecs; the only divergences are the documented Annex D quirks:
//! WinAnsi fills its undefined codes with `/bullet` and names 0xA0
//! `/space` and 0xAD `/hyphen`; MacRoman names 0xCA `/space` and keeps
//! 0xDB as `/currency` (pre-euro).
//!
//! Empty string = no name at that code (`.notdef`).

pub(crate) const WIN_ANSI_NAMES: [&str; 256] = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "space",
    "exclam",
    "quotedbl",
    "numbersign",
    "dollar",
    "percent",
    "ampersand",
    "quotesingle",
    "parenleft",
    "parenright",
    "asterisk",
    "plus",
    "comma",
    "hyphen",
    "period",
    "slash",
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "colon",
    "semicolon",
    "less",
    "equal",
    "greater",
    "question",
    "at",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "bracketleft",
    "backslash",
    "bracketright",
    "asciicircum",
    "underscore",
    "grave",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "braceleft",
    "bar",
    "braceright",
    "asciitilde",
    "bullet",
    "Euro",
    "bullet",
    "quotesinglbase",
    "florin",
    "quotedblbase",
    "ellipsis",
    "dagger",
    "daggerdbl",
    "circumflex",
    "perthousand",
    "Scaron",
    "guilsinglleft",
    "OE",
    "bullet",
    "Zcaron",
    "bullet",
    "bullet",
    "quoteleft",
    "quoteright",
    "quotedblleft",
    "quotedblright",
    "bullet",
    "endash",
    "emdash",
    "tilde",
    "trademark",
    "scaron",
    "guilsinglright",
    "oe",
    "bullet",
    "zcaron",
    "Ydieresis",
    "space",
    "exclamdown",
    "cent",
    "sterling",
    "currency",
    "yen",
    "brokenbar",
    "section",
    "dieresis",
    "copyright",
    "ordfeminine",
    "guillemotleft",
    "logicalnot",
    "hyphen",
    "registered",
    "macron",
    "degree",
    "plusminus",
    "twosuperior",
    "threesuperior",
    "acute",
    "mu",
    "paragraph",
    "periodcentered",
    "cedilla",
    "onesuperior",
    "ordmasculine",
    "guillemotright",
    "onequarter",
    "onehalf",
    "threequarters",
    "questiondown",
    "Agrave",
    "Aacute",
    "Acircumflex",
    "Atilde",
    "Adieresis",
    "Aring",
    "AE",
    "Ccedilla",
    "Egrave",
    "Eacute",
    "Ecircumflex",
    "Edieresis",
    "Igrave",
    "Iacute",
    "Icircumflex",
    "Idieresis",
    "Eth",
    "Ntilde",
    "Ograve",
    "Oacute",
    "Ocircumflex",
    "Otilde",
    "Odieresis",
    "multiply",
    "Oslash",
    "Ugrave",
    "Uacute",
    "Ucircumflex",
    "Udieresis",
    "Yacute",
    "Thorn",
    "germandbls",
    "agrave",
    "aacute",
    "acircumflex",
    "atilde",
    "adieresis",
    "aring",
    "ae",
    "ccedilla",
    "egrave",
    "eacute",
    "ecircumflex",
    "edieresis",
    "igrave",
    "iacute",
    "icircumflex",
    "idieresis",
    "eth",
    "ntilde",
    "ograve",
    "oacute",
    "ocircumflex",
    "otilde",
    "odieresis",
    "divide",
    "oslash",
    "ugrave",
    "uacute",
    "ucircumflex",
    "udieresis",
    "yacute",
    "thorn",
    "ydieresis",
];

pub(crate) const MAC_ROMAN_NAMES: [&str; 256] = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "space",
    "exclam",
    "quotedbl",
    "numbersign",
    "dollar",
    "percent",
    "ampersand",
    "quotesingle",
    "parenleft",
    "parenright",
    "asterisk",
    "plus",
    "comma",
    "hyphen",
    "period",
    "slash",
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "colon",
    "semicolon",
    "less",
    "equal",
    "greater",
    "question",
    "at",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "bracketleft",
    "backslash",
    "bracketright",
    "asciicircum",
    "underscore",
    "grave",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "braceleft",
    "bar",
    "braceright",
    "asciitilde",
    "",
    "Adieresis",
    "Aring",
    "Ccedilla",
    "Eacute",
    "Ntilde",
    "Odieresis",
    "Udieresis",
    "aacute",
    "agrave",
    "acircumflex",
    "adieresis",
    "atilde",
    "aring",
    "ccedilla",
    "eacute",
    "egrave",
    "ecircumflex",
    "edieresis",
    "iacute",
    "igrave",
    "icircumflex",
    "idieresis",
    "ntilde",
    "oacute",
    "ograve",
    "ocircumflex",
    "odieresis",
    "otilde",
    "uacute",
    "ugrave",
    "ucircumflex",
    "udieresis",
    "dagger",
    "degree",
    "cent",
    "sterling",
    "section",
    "bullet",
    "paragraph",
    "germandbls",
    "registered",
    "copyright",
    "trademark",
    "acute",
    "dieresis",
    "",
    "AE",
    "Oslash",
    "",
    "plusminus",
    "",
    "",
    "yen",
    "mu",
    "",
    "",
    "",
    "",
    "",
    "ordfeminine",
    "ordmasculine",
    "",
    "ae",
    "oslash",
    "questiondown",
    "exclamdown",
    "logicalnot",
    "",
    "florin",
    "",
    "",
    "guillemotleft",
    "guillemotright",
    "ellipsis",
    "space",
    "Agrave",
    "Atilde",
    "Otilde",
    "OE",
    "oe",
    "endash",
    "emdash",
    "quotedblleft",
    "quotedblright",
    "quoteleft",
    "quoteright",
    "divide",
    "",
    "ydieresis",
    "Ydieresis",
    "fraction",
    "currency",
    "guilsinglleft",
    "guilsinglright",
    "fi",
    "fl",
    "daggerdbl",
    "periodcentered",
    "quotesinglbase",
    "quotedblbase",
    "perthousand",
    "Acircumflex",
    "Ecircumflex",
    "Aacute",
    "Edieresis",
    "Egrave",
    "Iacute",
    "Icircumflex",
    "Idieresis",
    "Igrave",
    "Oacute",
    "Ocircumflex",
    "",
    "Ograve",
    "Uacute",
    "Ucircumflex",
    "Ugrave",
    "dotlessi",
    "circumflex",
    "tilde",
    "macron",
    "breve",
    "dotaccent",
    "ring",
    "cedilla",
    "hungarumlaut",
    "ogonek",
    "caron",
];

/// Adobe `StandardEncoding` (ISO 32000-1 Annex D.2, "StandardEncoding"
/// column). Consumed by the Type1 path: a font program declaring
/// `/Encoding StandardEncoding def`, and `seac` accent composition (whose
/// `bchar`/`achar` operands are StandardEncoding codes by definition).
/// Empty string = no name at that code (`.notdef`).
#[rustfmt::skip]
pub(crate) const STANDARD_NAMES: [&str; 256] = [
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "space", "exclam", "quotedbl", "numbersign", "dollar", "percent",
    "ampersand", "quoteright", "parenleft", "parenright", "asterisk", "plus",
    "comma", "hyphen", "period", "slash",
    "zero", "one", "two", "three", "four", "five", "six", "seven",
    "eight", "nine", "colon", "semicolon", "less", "equal", "greater",
    "question",
    "at", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
    "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
    "bracketleft", "backslash", "bracketright", "asciicircum", "underscore",
    "quoteleft", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l",
    "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
    "braceleft", "bar", "braceright", "asciitilde", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "exclamdown", "cent", "sterling", "fraction", "yen", "florin",
    "section", "currency", "quotesingle", "quotedblleft", "guillemotleft",
    "guilsinglleft", "guilsinglright", "fi", "fl",
    "", "endash", "dagger", "daggerdbl", "periodcentered", "", "paragraph",
    "bullet", "quotesinglbase", "quotedblbase", "quotedblright",
    "guillemotright", "ellipsis", "perthousand", "", "questiondown",
    "", "grave", "acute", "circumflex", "tilde", "macron", "breve",
    "dotaccent", "dieresis", "", "ring", "cedilla", "", "hungarumlaut",
    "ogonek", "caron",
    "emdash", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "AE", "", "ordfeminine", "", "", "", "", "Lslash", "Oslash", "OE",
    "ordmasculine", "", "", "", "",
    "", "ae", "", "", "", "dotlessi", "", "", "lslash", "oslash", "oe",
    "germandbls", "", "", "", "",
];

pub(crate) const NAME_TO_UNICODE: &[(&str, u32)] = &[
    ("A", 0x0041),
    ("AE", 0x00C6),
    ("Aacute", 0x00C1),
    ("Acircumflex", 0x00C2),
    ("Adieresis", 0x00C4),
    ("Agrave", 0x00C0),
    ("Aring", 0x00C5),
    ("Atilde", 0x00C3),
    ("B", 0x0042),
    ("C", 0x0043),
    ("Ccedilla", 0x00C7),
    ("D", 0x0044),
    ("E", 0x0045),
    ("Eacute", 0x00C9),
    ("Ecircumflex", 0x00CA),
    ("Edieresis", 0x00CB),
    ("Egrave", 0x00C8),
    ("Eth", 0x00D0),
    ("Euro", 0x20AC),
    ("F", 0x0046),
    ("G", 0x0047),
    ("H", 0x0048),
    ("I", 0x0049),
    ("Iacute", 0x00CD),
    ("Icircumflex", 0x00CE),
    ("Idieresis", 0x00CF),
    ("Igrave", 0x00CC),
    ("J", 0x004A),
    ("K", 0x004B),
    ("L", 0x004C),
    ("M", 0x004D),
    ("N", 0x004E),
    ("Ntilde", 0x00D1),
    ("O", 0x004F),
    ("OE", 0x0152),
    ("Oacute", 0x00D3),
    ("Ocircumflex", 0x00D4),
    ("Odieresis", 0x00D6),
    ("Ograve", 0x00D2),
    ("Oslash", 0x00D8),
    ("Otilde", 0x00D5),
    ("P", 0x0050),
    ("Q", 0x0051),
    ("R", 0x0052),
    ("S", 0x0053),
    ("Scaron", 0x0160),
    ("T", 0x0054),
    ("Thorn", 0x00DE),
    ("U", 0x0055),
    ("Uacute", 0x00DA),
    ("Ucircumflex", 0x00DB),
    ("Udieresis", 0x00DC),
    ("Ugrave", 0x00D9),
    ("V", 0x0056),
    ("W", 0x0057),
    ("X", 0x0058),
    ("Y", 0x0059),
    ("Yacute", 0x00DD),
    ("Ydieresis", 0x0178),
    ("Z", 0x005A),
    ("Zcaron", 0x017D),
    ("a", 0x0061),
    ("aacute", 0x00E1),
    ("acircumflex", 0x00E2),
    ("acute", 0x00B4),
    ("adieresis", 0x00E4),
    ("ae", 0x00E6),
    ("agrave", 0x00E0),
    ("ampersand", 0x0026),
    ("aring", 0x00E5),
    ("asciicircum", 0x005E),
    ("asciitilde", 0x007E),
    ("asterisk", 0x002A),
    ("at", 0x0040),
    ("atilde", 0x00E3),
    ("b", 0x0062),
    ("backslash", 0x005C),
    ("bar", 0x007C),
    ("braceleft", 0x007B),
    ("braceright", 0x007D),
    ("bracketleft", 0x005B),
    ("bracketright", 0x005D),
    ("breve", 0x02D8),
    ("brokenbar", 0x00A6),
    ("bullet", 0x2022),
    ("c", 0x0063),
    ("caron", 0x02C7),
    ("ccedilla", 0x00E7),
    ("cedilla", 0x00B8),
    ("cent", 0x00A2),
    ("circumflex", 0x02C6),
    ("colon", 0x003A),
    ("comma", 0x002C),
    ("copyright", 0x00A9),
    ("currency", 0x00A4),
    ("d", 0x0064),
    ("dagger", 0x2020),
    ("daggerdbl", 0x2021),
    ("degree", 0x00B0),
    ("dieresis", 0x00A8),
    ("divide", 0x00F7),
    ("dollar", 0x0024),
    ("dotaccent", 0x02D9),
    ("dotlessi", 0x0131),
    ("e", 0x0065),
    ("eacute", 0x00E9),
    ("ecircumflex", 0x00EA),
    ("edieresis", 0x00EB),
    ("egrave", 0x00E8),
    ("eight", 0x0038),
    ("ellipsis", 0x2026),
    ("emdash", 0x2014),
    ("endash", 0x2013),
    ("equal", 0x003D),
    ("eth", 0x00F0),
    ("exclam", 0x0021),
    ("exclamdown", 0x00A1),
    ("f", 0x0066),
    ("fi", 0xFB01),
    ("five", 0x0035),
    ("fl", 0xFB02),
    ("florin", 0x0192),
    ("four", 0x0034),
    ("fraction", 0x2044),
    ("g", 0x0067),
    ("germandbls", 0x00DF),
    ("grave", 0x0060),
    ("greater", 0x003E),
    ("guillemotleft", 0x00AB),
    ("guillemotright", 0x00BB),
    ("guilsinglleft", 0x2039),
    ("guilsinglright", 0x203A),
    ("h", 0x0068),
    ("hungarumlaut", 0x02DD),
    ("hyphen", 0x002D),
    ("i", 0x0069),
    ("iacute", 0x00ED),
    ("icircumflex", 0x00EE),
    ("idieresis", 0x00EF),
    ("igrave", 0x00EC),
    ("j", 0x006A),
    ("k", 0x006B),
    ("l", 0x006C),
    ("less", 0x003C),
    ("logicalnot", 0x00AC),
    ("m", 0x006D),
    ("macron", 0x00AF),
    ("mu", 0x00B5),
    ("multiply", 0x00D7),
    ("n", 0x006E),
    ("nine", 0x0039),
    ("ntilde", 0x00F1),
    ("numbersign", 0x0023),
    ("o", 0x006F),
    ("oacute", 0x00F3),
    ("ocircumflex", 0x00F4),
    ("odieresis", 0x00F6),
    ("oe", 0x0153),
    ("ogonek", 0x02DB),
    ("ograve", 0x00F2),
    ("one", 0x0031),
    ("onehalf", 0x00BD),
    ("onequarter", 0x00BC),
    ("onesuperior", 0x00B9),
    ("ordfeminine", 0x00AA),
    ("ordmasculine", 0x00BA),
    ("oslash", 0x00F8),
    ("otilde", 0x00F5),
    ("p", 0x0070),
    ("paragraph", 0x00B6),
    ("parenleft", 0x0028),
    ("parenright", 0x0029),
    ("percent", 0x0025),
    ("period", 0x002E),
    ("periodcentered", 0x00B7),
    ("perthousand", 0x2030),
    ("plus", 0x002B),
    ("plusminus", 0x00B1),
    ("q", 0x0071),
    ("question", 0x003F),
    ("questiondown", 0x00BF),
    ("quotedbl", 0x0022),
    ("quotedblbase", 0x201E),
    ("quotedblleft", 0x201C),
    ("quotedblright", 0x201D),
    ("quoteleft", 0x2018),
    ("quoteright", 0x2019),
    ("quotesinglbase", 0x201A),
    ("quotesingle", 0x0027),
    ("r", 0x0072),
    ("registered", 0x00AE),
    ("ring", 0x02DA),
    ("s", 0x0073),
    ("scaron", 0x0161),
    ("section", 0x00A7),
    ("semicolon", 0x003B),
    ("seven", 0x0037),
    ("six", 0x0036),
    ("slash", 0x002F),
    ("space", 0x0020),
    ("sterling", 0x00A3),
    ("t", 0x0074),
    ("thorn", 0x00FE),
    ("three", 0x0033),
    ("threequarters", 0x00BE),
    ("threesuperior", 0x00B3),
    ("tilde", 0x02DC),
    ("trademark", 0x2122),
    ("two", 0x0032),
    ("twosuperior", 0x00B2),
    ("u", 0x0075),
    ("uacute", 0x00FA),
    ("ucircumflex", 0x00FB),
    ("udieresis", 0x00FC),
    ("ugrave", 0x00F9),
    ("underscore", 0x005F),
    ("v", 0x0076),
    ("w", 0x0077),
    ("x", 0x0078),
    ("y", 0x0079),
    ("yacute", 0x00FD),
    ("ydieresis", 0x00FF),
    ("yen", 0x00A5),
    ("z", 0x007A),
    ("zcaron", 0x017E),
    ("zero", 0x0030),
];

/// AGL name -> Unicode for the names of the two supported base encodings.
/// Also accepts the `uniXXXX` / `uXXXX[XX]` self-describing name forms used
/// by `/Differences` arrays. `None` = unknown name (caller must fail safe).
pub(crate) fn glyph_name_to_unicode(name: &[u8]) -> Option<u32> {
    let name = std::str::from_utf8(name).ok()?;
    if let Ok(idx) = NAME_TO_UNICODE.binary_search_by(|(n, _)| n.cmp(&name)) {
        return Some(NAME_TO_UNICODE[idx].1);
    }
    // uniXXXX: exactly four uppercase hex digits (AGL specification); uXXXX to
    // uXXXXXX: four to six uppercase hex digits.
    let parse_hex = |s: &str, min: usize, max: usize| -> Option<u32> {
        if s.len() < min
            || s.len() > max
            || !s
                .bytes()
                .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_lowercase())
        {
            return None;
        }
        let v = u32::from_str_radix(s, 16).ok()?;
        // Surrogates are not scalar values; anything above the last plane is
        // not a character at all.
        if (0xD800..=0xDFFF).contains(&v) || v > 0x10_FFFF {
            None
        } else {
            Some(v)
        }
    };
    if let Some(rest) = name.strip_prefix("uni") {
        return parse_hex(rest, 4, 4);
    }
    if let Some(rest) = name.strip_prefix("u") {
        return parse_hex(rest, 4, 6);
    }
    None
}

/// Inverse MacRomanEncoding: glyph name -> code, for the `(1,0)` cmap lookup
/// path (ISO 32000-1 9.6.6.4: the name is looked up in the standard Mac OS
/// Roman encoding to obtain a code). First occurrence wins (`/space` appears
/// at both 0x20 and 0xCA; viewers use the canonical 0x20).
pub(crate) fn mac_roman_code_of(name: &[u8]) -> Option<u8> {
    MAC_ROMAN_NAMES
        .iter()
        .position(|&n| !n.is_empty() && n.as_bytes() == name)
        .map(|idx| idx as u8)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn name_table_is_sorted_for_binary_search() {
        for pair in NAME_TO_UNICODE.windows(2) {
            assert!(
                pair[0].0 < pair[1].0,
                "NAME_TO_UNICODE must be strictly sorted"
            );
        }
    }

    #[test]
    fn annex_d_quirks_hold() {
        // The documented Annex D quirks double as canaries against table
        // regeneration errors.
        assert_eq!(WIN_ANSI_NAMES[0xA0], "space");
        assert_eq!(WIN_ANSI_NAMES[0xAD], "hyphen");
        assert_eq!(WIN_ANSI_NAMES[0x81], "bullet");
        assert_eq!(WIN_ANSI_NAMES[0x41], "A");
        assert_eq!(WIN_ANSI_NAMES[0x80], "Euro");
        assert_eq!(MAC_ROMAN_NAMES[0xCA], "space");
        assert_eq!(MAC_ROMAN_NAMES[0xDB], "currency");
        assert_eq!(MAC_ROMAN_NAMES[0xA5], "bullet");
        assert_eq!(glyph_name_to_unicode(b"space"), Some(0x20));
        assert_eq!(glyph_name_to_unicode(b"hyphen"), Some(0x2D));
        assert_eq!(glyph_name_to_unicode(b"Euro"), Some(0x20AC));
        assert_eq!(glyph_name_to_unicode(b"quotesingle"), Some(0x27));
        assert_eq!(glyph_name_to_unicode(b"adieresis"), Some(0xE4));
        assert_eq!(glyph_name_to_unicode(b"uni20AC"), Some(0x20AC));
        assert_eq!(glyph_name_to_unicode(b"u1D400"), Some(0x1D400));
        assert_eq!(
            glyph_name_to_unicode(b"uni20ac"),
            None,
            "AGL uniXXXX is uppercase-only"
        );
        assert_eq!(glyph_name_to_unicode(b"no-such-glyph"), None);
        assert_eq!(mac_roman_code_of(b"space"), Some(0x20));
        assert_eq!(mac_roman_code_of(b"bullet"), Some(0xA5));
        assert_eq!(mac_roman_code_of(b"A"), Some(0x41));
        assert_eq!(
            mac_roman_code_of(b"Euro"),
            None,
            "MacRomanEncoding has no Euro"
        );
    }
}
